name: Space ID App S3 Deploy - Staging

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.FE_DEPLOYER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run build:stg

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: 'build'
          bucket: 'stg-preregi-space-id'
          bucket-region: 'us-west-2'
          dist-id: 'ESH7K4VJTGCUU'
          invalidation: /
          delete-removed: true
          no-cache: false
          private: true
          # bucket: 'stg-app-space-id'
          # bucket-region: 'us-west-2'
          # dist-id: 'EQQRPZMXDBL2P'
          # invalidation: /
          # bucket: 'stg-preregi-space-id'
          # bucket-region: 'us-west-2'
          # dist-id: 'ESH7K4VJTGCUU'
          # invalidation: /app/
